[package]
name = "scoop"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
owo-colors = "4.2.2"
serde = { version = "1.0.219", features = ["derive"] }
